Add functions to import spectrometer data and create intensity summary
OsmoSystems/osmo-jupyter pull request #11
Opened 2019-01-22 18:46 UTC by jacob-r-g

**Work**
- Created function to preprocess and import raw spectrometer txt file
- Created function to create intensity summary from imported spectrometer data 

**Testing**
- Added and ran new automated tests 

**ToDo**
- Manually test in a jupyter notebook

2019-01-22 19:11 UTC, jaimemarijke reviewed
A bunch of small comments. 
I'll someone else giving an Approving review since I paired with you on this

2019-01-22 19:11 UTC, jaimemarijke commented on osmo_jupyter/mock_bad_spectrometer_data.txt
> +2019-01-07 16:13:37.597000	1546906417597	-626	627	-163.15
We talked about this but forgot to do it: probably we should move these files into a new "text_fixtures" folder, e.g.:  `/osmo_jupyter/test_fixtures/mock_bad_spectrometer_data.txt`. (You'll need to update the test code that specifies where to find these files as well).

2019-01-22 19:11 UTC, jaimemarijke commented on osmo_jupyter/spectrometer.py
> +    with open(spectrometer_data_file_path, 'r', newline=None) as infile:
Should add a comment above this line that explains why we had to do this: e.g.
`# The raw spectrometer file contains mixed "\r\n" and "\n" line endings. Open file with newline=None to ensure all line endings are "\n"`

2019-01-22 19:11 UTC, jaimemarijke commented on osmo_jupyter/spectrometer.py
> +            if line.strip() == '>>>>>Begin Spectral Data<<<<<':
probably this string should be a named constant, e.g.

`SPECTRAL_DATA_IDENTIFIER = '>>>>>Begin Spectral Data<<<<<'`

2019-01-22 19:11 UTC, jaimemarijke commented on osmo_jupyter/spectrometer.py
> +        for line in infile:
this loop should also have a comment, e.g.
`# Read through file metadata until we find the marker that identifies the start of the tab-delimited data`

2019-01-22 19:11 UTC, jaimemarijke commented on osmo_jupyter/spectrometer.py
> +                    io.StringIO(file_content_with_unix_endings),
could probably skip the temporary variable `file_content_with_unix_endings` and just have this line directly call `infile.read()`

2019-01-22 19:11 UTC, jaimemarijke commented on osmo_jupyter/spectrometer.py
> +
extra newline?

2019-01-22 19:11 UTC, jaimemarijke commented on osmo_jupyter/spectrometer.py
> +        # timestamp column is in local time, epoch_time column is in UTC
nit: comments should start with capitals.
Also... it makes me slightly nervous to be using the local timestamp instead of the UTC one. I wonder if we should switch to using the UTC epoch time and convert to a timezone-aware datetime

2019-01-22 19:11 UTC, jaimemarijke commented on osmo_jupyter/spectrometer.py
> +    # Remove redundant timestamp column
nit: timestamp --> epoch_time

2019-01-22 19:11 UTC, jaimemarijke commented on osmo_jupyter/spectrometer.py
> +    ''' Reformats a df of spectrometer data with many wavelength columns,to a more useful format with 2 columns
nit: "columns,to" --> "columns, to"

2019-01-22 19:11 UTC, jaimemarijke commented on osmo_jupyter/spectrometer.py
> +    reformatted_spectrometer_data = _reformat_spectrometer_data(spectrometer_data_with_clean_header)
nice, I like this sequential structure better - the named temporary variables help me understand the sequence of steps that are occurring here

2019-01-22 19:11 UTC, jaimemarijke commented on osmo_jupyter/spectrometer.py
> +def spectrometer_intensity_summary(reformatted_spectrometer_data, minimum_wavelength=340, maximum_wavelength=1035):
nit: the default kwargs here feel like "magic numbers" - as a reader I don't know why those particular values were chosen.
If they are arbitrary, I'd probably just remove them. Or if you want either bound to be optional, then set them to "None" and have the code interpret that as unbounded.
If they have some physical basis, e.g. they are the min and max values that it is possible to read on the spectrometer, you could save them as named constants, e.g.
```
MIN_SPECTROMETER_WAVELENGTH=340
MAX_SPECTROMETER_WAVELENGTH=1035
...
def spectrometer_intensity_summary(reformatted_spectrometer_data, minimum_wavelength=MIN_SPECTROMETER_WAVELENGTH, maximum_wavelength=MAX_SPECTROMETER_WAVELENGTH):
```

2019-01-22 19:11 UTC, jaimemarijke commented on osmo_jupyter/spectrometer.py
> +    # Question whether or not this should be mean. An integral may relate more closely to a useful unit
TODO: answer this question, or at least change the comment to describe the rationale for choosing "mean()" for now

2019-01-22 19:11 UTC, jaimemarijke commented on osmo_jupyter/spectrometer_test.py
> +    expected_formatted_spectrometer_data = pd.DataFrame({
since the exact same DataFrame is used in three tests, it would probably be good to pull it out to a named module-level constant so that you don't have to define it multiple times, e.g. 

```
FORMATTED_SPECTROMETER_DF = pd.DataFrame({...})
...
assert actual == FORMATTED_SPECTROMETER_DF
```

2019-01-22 19:11 UTC, jaimemarijke commented on osmo_jupyter/spectrometer_test.py
> +        minimum_wavelength=344,
depending on what you decide to do about the default kwargs in the actual code, I might recommend a "parameterized" test that exercises multiple code paths, e.g. including both max & min, including just one of max or min, including neither max nor min.

If you go that route, I can show you how to quickly update this test to do that.

2019-01-22 20:17 UTC, jason-curtis requested changes
mostly looks great!
lots of small things, the big ones are to move the .txt fixtures to a `fixtures` or `test_fixtures` directory and to make sure you're testing all the kwargs in that last test case.

2019-01-22 20:17 UTC, jason-curtis commented on osmo_jupyter/mock_bad_spectrometer_data.txt
> +2019-01-07 16:13:37.597000	1546906417597	-626	627	-163.15
+1

2019-01-22 20:17 UTC, jason-curtis commented on osmo_jupyter/mock_spectrometer_data.txt
> +2019-01-07 16:13:47.496000	1546906427496	-546.47	-546.47	189.1
as mentioned in person, plz confirm that this has mixed line endings even in git, since tools sometimes normalize them without telling you. maybe not a huge deal if they're not mixed, but it'd at least be good to know.

2019-01-22 20:17 UTC, jason-curtis commented on osmo_jupyter/spectrometer.py
> +    # Remove redundant timestamp column
if you do this, it'd be nice to explicitly point out that it's redundant to the timestamp column
```suggestion
    # 'epoch_time' column is redundant to 'timestamp' column. Remove it
```

2019-01-22 20:17 UTC, jason-curtis commented on osmo_jupyter/spectrometer.py
> +    ''' Cleans up header of raw spectrometer data, and removes redundant timestamp column.
nice one-liner :)

2019-01-22 20:17 UTC, jason-curtis commented on osmo_jupyter/spectrometer.py
> +    # Question whether or not this should be mean. An integral may relate more closely to a useful unit
+1, I think mean is fine. I'd be tempted to upgrade the function to divide by the bin width to actually give the mean value per nanometer wavelength, but I think it's also fine to keep this as-is.

2019-01-22 20:17 UTC, jason-curtis commented on osmo_jupyter/spectrometer_test.py
> +class TestImportSpectrometerData:
nice, I love how simple and convincing these integration tests are 👍 👍

2019-01-22 20:17 UTC, jason-curtis commented on osmo_jupyter/spectrometer_test.py
> +            -546.47,
you could simplify this test and the fixture, and make the results more self-evidently correct, by using only 2 timestamps and using round numbers that are easier to check that they're obviously correct.

2019-01-22 20:17 UTC, jason-curtis commented on osmo_jupyter/spectrometer_test.py
> +        minimum_wavelength=344,
+1 to this, it looks like you're only actually testing `maximum_wavelength` here but I'm not 100% sure since I'm too lazy to check the math (see later comment re: using round numbers when reasonable).
also happy to help you parameterize this though you could also just search for examples where we use `pytest.mark.parametrize`(sic).

2019-01-22 20:17 UTC, jason-curtis commented on osmo_jupyter/mock_spectrometer_data.txt
> +2019-01-07 16:13:47.496000	1546906427496	-546.47	-546.47	189.1
(you checked, they're still there, all good!)

2019-01-22 22:10 UTC, dubchuck reviewed
Mostly nits.

2019-01-22 22:10 UTC, dubchuck commented on osmo_jupyter/spectrometer.py
> +                file_content_with_unix_endings = infile.read()
I believe this variable name is a bit over-descriptive, ```file_content``` would probably suffice.

Also there probably is not a guarantee there would always be ```unix_endings```.

2019-01-22 22:10 UTC, dubchuck commented on osmo_jupyter/spectrometer.py
> +                    io.StringIO(file_content_with_unix_endings),
+1

2019-01-22 22:10 UTC, dubchuck commented on osmo_jupyter/spectrometer.py
> +        unformatted_spectrometer_data: a pandas df of original spectrometer data,
```_df``` suffix instead of ```_data```?

2019-01-22 22:26 UTC, jacob-r-g commented on osmo_jupyter/mock_bad_spectrometer_data.txt
> +2019-01-07 16:13:37.597000	1546906417597	-626	627	-163.15
definitely makes sense! worried about the problem we ran into earlier where pytest looks for anything with the prefix 'test_' any other suggestions for names? maybe testing_fixtures?

2019-01-22 22:27 UTC, jacob-r-g commented on osmo_jupyter/spectrometer.py
> +    with open(spectrometer_data_file_path, 'r', newline=None) as infile:
awesome. thanks!

2019-01-22 22:30 UTC, jacob-r-g commented on osmo_jupyter/spectrometer.py
> +                    io.StringIO(file_content_with_unix_endings),
sounds good

2019-01-22 22:30 UTC, jacob-r-g commented on osmo_jupyter/spectrometer.py
> +        for line in infile:
good call!

2019-01-22 22:30 UTC, jacob-r-g commented on osmo_jupyter/spectrometer.py
> +            if line.strip() == '>>>>>Begin Spectral Data<<<<<':
make sense

2019-01-22 22:34 UTC, jacob-r-g commented on osmo_jupyter/spectrometer.py
> +def spectrometer_intensity_summary(reformatted_spectrometer_data, minimum_wavelength=340, maximum_wavelength=1035):
makes sense!

2019-01-22 22:41 UTC, jacob-r-g commented on osmo_jupyter/spectrometer_test.py
> +    expected_formatted_spectrometer_data = pd.DataFrame({
nice! good call

2019-01-22 22:42 UTC, jaimemarijke commented on osmo_jupyter/mock_bad_spectrometer_data.txt
> +2019-01-07 16:13:37.597000	1546906417597	-626	627	-163.15
I *think* that was because the file itself was prefixed with `test_` instead of `mock_`. I don't remember if pytest cares about folder names. I'd try the folder name `test_fixtures` and see if it works, and if not, just call it "fixtures"

2019-01-22 22:45 UTC, jaimemarijke commented on osmo_jupyter/spectrometer_test.py
> +            -546.47,
+1, I know it's annoying and you avoided changing the test file b/c of the line ending issue, but it's probably worth it to edit it to pick numbers that are easier to deal with

2019-01-22 22:51 UTC, jacob-r-g commented on osmo_jupyter/spectrometer_test.py
> +            -546.47,
great point, and well taken. The rationale for not doing that is consistency. Nice to use the same test data for multiple tests where possible, which should be more evident now that this test function accepts the module level FORMATTED_SPECTROMETER_DF variable...

willing to change it if its too unclear though

2019-01-22 22:52 UTC, jacob-r-g commented on osmo_jupyter/spectrometer.py
> +                file_content_with_unix_endings = infile.read()
changed and added a comment for clarity on what's happening

2019-01-22 22:54 UTC, jacob-r-g commented on osmo_jupyter/spectrometer.py
> +        unformatted_spectrometer_data: a pandas df of original spectrometer data,
yes! great suggestion.

2019-01-22 23:21 UTC, jacob-r-g commented on osmo_jupyter/spectrometer_test.py
> +        minimum_wavelength=344,
have glanced through some examples used and still feel like i could use a bit of hand holding. would love to grab either one of you for a few minutes for tips on this

2019-01-24 01:29 UTC, jacob-r-g commented on osmo_jupyter/spectrometer.py
> +        # timestamp column is in local time, epoch_time column is in UTC
nit: addressed. 

I hear ya on the local time. A redeeming factor for me is that the timestamp for the spectrometer data is set by the MSI which is set automatically... in other words, was just matching the protocol of our timestamps for our image data (image exif data set to local time by Pi) What do you think?

2019-01-24 02:09 UTC, jason-curtis commented on osmo_jupyter/spectrometer_test.py
> +        mock_spectrometer_df = pd.DataFrame({
You're using "test" and "mock" here in non-standard ways which I found confusing.
More standard names for this would be `actual_spectrometer_df` and `expected_spectrometer_df` or even just `actual` and `expected`.

2019-01-24 02:09 UTC, jason-curtis commented on osmo_jupyter/spectrometer_test.py
> +            -546.47,
Makes sense. Ultimately that gets you something in making sure that all of the data sets are similarly realistic, but in the long term it usually ends up being worth it for test cases to be decoupled from one another and have their own tailored fixtures, since they can be much simpler -> easier to understand and maintain, and it makes it easier to test edge cases without updating a bunch of other tests. I think this is fine for now but I reserve the right to make other tests that don't use the same fixture in the future.

2019-01-24 02:09 UTC, jason-curtis approved these changes
just one super minor thing leftttt

2019-01-24 17:08 UTC, jacob-r-g commented on osmo_jupyter/spectrometer_test.py
> +            -546.47,
That makes sense. Thanks for explaining

2019-01-25 04:01 UTC, dubchuck approved these changes
Great work @jacob-r-g!  🚢 👍 ✈️ 🕺 💃

2019-01-25 04:31 UTC, merged