Added heatmapify function + tests
OsmoSystems/osmo-jupyter pull request #15
Opened 2019-03-08 00:47 UTC by jaimemarijke

**Work**
* Copy over existing heatmap code from [Heatmap example](https://drive.google.com/drive/u/0/folders/1cZnlonCBPF1HdZw6myvkTZMma4eEdufI)
* Refactor a bit
* Write automated tests

**Discussion questions**
* I chose to leave out the code that slices an image by channel, and instead have the `heatmapify` function take just a 2D array. I could be convinced that the function should instead take `image` and `channel` params and do the slicing itself (that's how I originally wrote it). Opinions?
* I did a bit of refactoring on the existing code, but tried to limit it. Should I do more to make it cleaner / easier to read?

**Testing**
* Automated unit tests for `get_block_means_2d` and `cut_array2d`
* Automated smoke/integration test for `heatmapify`
* No automated tests for `display_heatmap`
* In a jupyter notebook, manually tested that heatmapify function works and is equivalent to old jupyter snippet

2019-03-08 01:07 UTC, jason-curtis requested changes
test request is the only real "change requested". the other thing is minor
I did not read the code in too much detail - mostly assumed that things were not changed from the original implementation

2019-03-08 01:07 UTC, jason-curtis commented on osmo_jupyter/plot/heatmap.py
> +        ((ycut[i] + ycut[i+1] - 1) / 2, (xcut[j] + xcut[j+1] - 1) / 2)
hmmmm, this would be kind of iffy in a code sample. any way you could make it better? 
maybe just more newlines?

---- musing below this point. feel free to ignore ----
I see now how `xcut` and `ycut` are actually not really like grid lines, since they are *on* the grid cells rather than next to them. if they were each increased by 0.5, then you wouldn't have to do this here. But then the actual indexing on line 35 would get mad since slice indices have to be integers. That thought cleared things up for me a bit but didn't make this line feel better... probably newlines are the main way to go.

2019-03-08 01:07 UTC, jason-curtis commented on osmo_jupyter/plot/heatmap_test.py
> +    def test_cut_odd_shape(self):
sick test suite.
I like how you used integers to clarify your intent, but there's a weakness there too. Maybe you want one test case which makes sure that the order of elements isn't messed up within a block?

2019-03-11 15:59 UTC, jaimemarijke commented on osmo_jupyter/plot/heatmap.py
> +        ((ycut[i] + ycut[i+1] - 1) / 2, (xcut[j] + xcut[j+1] - 1) / 2)
Bleh, yeah, I was really tempted to sink time into trying to make this clearer, but in the ~5 minutes I spent thinking of it I didn't come up with anything great. 

Added newlines - do they help at all?

2019-03-11 16:07 UTC, jason-curtis approved these changes

2019-03-11 17:43 UTC, jason-curtis commented on osmo_jupyter/plot/heatmap.py
> +        ((ycut[i] + ycut[i+1] - 1) / 2, (xcut[j] + xcut[j+1] - 1) / 2)
yeah it does help. I think it's good enough

2019-03-11 20:39 UTC, dubchuck commented on osmo_jupyter/plot/heatmap.py
> +    # Think, gridlines:
Nit: Could be a little bit more descriptive here.

2019-03-11 20:46 UTC, dubchuck approved these changes
A few questionable nits but LGTM

2019-03-11 20:46 UTC, dubchuck commented on osmo_jupyter/plot/heatmap.py
> +        shape of the array, drops data from the right and bottom edges of the input `array`.
Not a strong opinion but it feels that if the data from the right and bottom edges needs to be dropped it should be done within separate method.

2019-03-11 20:46 UTC, dubchuck commented on osmo_jupyter/plot/heatmap.py
> +def display_heatmap(array, display_decimals=2, title='Heatmap'):
Possible nit: ```array``` could be more descriptive?

2019-03-11 20:46 UTC, dubchuck commented on osmo_jupyter/plot/heatmap.py
> +def heatmapify(array, block_shape=(50, 50), display_decimals=2, title='Heatmap'):
Same nit as above

2019-03-11 21:45 UTC, jason-curtis approved these changes

2019-03-11 21:45 UTC, jason-curtis commented on osmo_jupyter/plot/heatmap.py
> +        averaging_function: Optional (default=np.mean). Function to use to get the average of each block
might want to mention that it will be called with a 2d array

2019-03-11 21:49 UTC, jaimemarijke commented on osmo_jupyter/plot/heatmap.py
> +def display_heatmap(array, display_decimals=2, title='Heatmap'):
I had that thought too, but couldn't come up with a better name. Maybe `array_to_heatmapify`?

2019-03-11 23:31 UTC, merged