Add tools for processing calibration data
OsmoSystems/osmo-jupyter pull request #33
Opened 2019-08-15 17:59 UTC by EvanSimpson

[Asana Ticket](https://app.asana.com/0/819671808102776/1135264514117500)

Adds some helper tools for processing all of our various sources of data into neat datasets.
Tests feel pretty messy and coverage a little light due to the amount of mock data necessary to adequately test a lot of this functionality. 

Also open to feedback re: spitting up / renaming the module.

## Manual Testing
See some example usage on our most recent collection of data in `Move some dataset generation code into osmo-jupyter.ipynb` [here](https://drive.google.com/drive/u/0/folders/1aZ3WLY2amdifzrmaQIp_5pRbanRh2N2K)

2019-08-15 18:00 UTC, EvanSimpson commented on osmo_jupyter/dataset.py
> +    images = pivot["image"][experiment_df["ROI"].values[0]]
I looked into instead doing this transform with a `groupby` and `apply`ing the pivot to clean up this messy bit at the end, but the performance was significantly worse than just pivoting everything altogether.

2019-08-15 19:12 UTC, jason-curtis requested changes
awaiting docstrings

2019-08-15 19:12 UTC, jason-curtis commented on osmo_jupyter/dataset.py
> +def get_equilibration_boundaries(equilibration_status: pd.Series) -> pd.DataFrame:
it would be good to have a docstring for this, it wasn't initially clear why using this was better than just joining first and then filtering. something like 
``` Get a DataFrame of equilibration periods with their leading and trailing edges
Takes a conservative approach, assuming all time between unequilibrated and equilibrated input points are unequilibrated.
```

2019-08-15 19:12 UTC, jason-curtis commented on osmo_jupyter/dataset.py
> +    interpolated_equilbration_status = equilibration_status_sampler.interpolate().apply(
it's not clear to me that we need to interpolate. it feels like the end result of the truncation scheme here is that the timestamps in the output where the equilibration status changes, are the same as the timestamps on the inputs where the status changed:

```
original: 0      0     1     1    0
interp'd: 0000000000000111111100000
diff()  : 0000000000000+000000-0000
leading:               *
diff(-1): 0000000000001000000+00000
trailing:                    *
```
so if you skipped this step and then just used `equilibrated_mask` on lines 79 and onwards, wouldn't you get just about the same thing?

Also we may want to consider if there are repercussions here for how we should structure the calibration runner. There may be edge cases in which we're telling the pi to take pictures but which won't count as equilibrated by this metric. Which brings up the question - do we expect to actually use this function once Michael's current work lands?

2019-08-15 19:12 UTC, jason-curtis commented on osmo_jupyter/dataset_test.py
> +        test_equilibration_boundaries = pd.DataFrame(
nit: why'd you construct a `DataFrame` here with one row and then use `.iloc`? Why not just make a `Series` in the first place?

2019-08-15 20:48 UTC, jason-curtis approved these changes
nothin' major! I only did a fairly cursory look at the tests.

2019-08-15 20:48 UTC, jason-curtis commented on osmo_jupyter/dataset.py
> +        trailing_edges = trailing_edges[1:]
minor: this stuff feels like it wants a parameterized test case

2019-08-15 20:48 UTC, jason-curtis commented on osmo_jupyter/dataset.py
> +            process_experiment_result_filepaths: A list of filepaths to process experiment summary statistics files.
Not sure what'll happen if ROIs don't match; do you know? I'm fine leaving it explicitly undefined
```suggestion
            process_experiment_result_filepaths: A list of filepaths to process experiment summary statistics files.
                These are all expected to have the same ROIs.
```

2019-08-15 20:48 UTC, jason-curtis commented on osmo_jupyter/dataset.py
> +    pivot.columns = [" ".join(col[::-1]).strip() for col in pivot.columns.values]
minor: logic here is a little surprising. not sure if black will let you sneak a comment in there but it'd be nice
```suggestion
    pivot.columns = [
       # ("r_msorm", "some ROI name") -> "some ROI name r_msorm"
        " ".join(col[::-1]).strip()
        for col in pivot.columns.values
    ]
```

2019-08-15 20:48 UTC, jason-curtis commented on osmo_jupyter/dataset.py
> +    images = pivot["image"][experiment_df["ROI"].values[0]]
minor: I'm definitely struggling to picture the DF in each stage of this transformation. maybe a couple more comments would help (right now my sticking point is imagining exactly what the indices are after the pivot and how those end up as columns on line 140)? or not; I think the unit test and docstring convince me this is doing the right thing.

2019-08-15 20:48 UTC, jason-curtis commented on osmo_jupyter/dataset.py
> +            for experiment_name in experiment_names
nit: it might be slightly more straightforward to just construct this DF straight-up with a nested list comprehension... but that option invokes less broadcasting magic :)
`pd.DataFrame([{...} for experiment in experiments for image in os.listdir(...)`

2019-08-15 20:48 UTC, jason-curtis commented on osmo_jupyter/dataset.py
> +    return df[leading_edge_mask & trailing_edge_mask]
I :heart: pandas/numpy

2019-08-15 20:48 UTC, jason-curtis commented on osmo_jupyter/dataset.py
> +            A fitlered df containing only values whose index is between the given start_time and end_tim.
nit. typing a little fast now, are we
```suggestion
            A filtered df containing only values whose index is between the given start_time and end_time.
```

2019-08-15 20:48 UTC, jason-curtis commented on osmo_jupyter/dataset.py
> +                dtype="object",  # Ensure correct dtype when no images are found
minor: looks like there's another edge case here that could use a regression test

2019-08-15 21:15 UTC, EvanSimpson commented on osmo_jupyter/dataset.py
> +            process_experiment_result_filepaths: A list of filepaths to process experiment summary statistics files.
Oh, I think it will just produce a bunch on NaN values. I can verify, but I'll add a comment about that.

2019-08-16 20:52 UTC, rush340 approved these changes
Looks good!

2019-08-16 20:52 UTC, rush340 commented on osmo_jupyter/dataset.py
> +    msorm_types: List[str] = ["r_msorm", "g_msorm", "b_msorm"],
minor: mutable defaults make me nervous (since all callers get the same instance). Could set to None and assign in the function, or use a tuple for the default.

2019-08-16 20:52 UTC, rush340 commented on osmo_jupyter/dataset.py
> +    msorm_types: List[str] = ["r_msorm", "g_msorm", "b_msorm"],
same as above

2019-08-16 20:52 UTC, rush340 commented on osmo_jupyter/dataset.py
> +    # After pivot -> Multi-level index
These comments are very helpful!

2019-08-16 20:52 UTC, rush340 commented on osmo_jupyter/dataset.py
> +        trailing_edges = trailing_edges[1:]
Could we instead add the first item to leading edges (or last item to trailing edges in the "if" below this) so that we don't lose equilibrated ranges at the beginning/end of a dataset?

2019-08-19 14:54 UTC, EvanSimpson commented on osmo_jupyter/dataset.py
> +        trailing_edges = trailing_edges[1:]
I think duplicating a final leading edge to also be a trailing edge makes sense, since that could come up if the calibration software crashed in an equilibrated state, but I'm hesitant about keeping data that starts out equilibrated. In theory that shouldn't ever happen and would mean the data had been corrupted, since you have to have 5 minutes of samples before anything is labeled as equilibrated, right?

2019-08-19 17:28 UTC, jason-curtis commented on osmo_jupyter/dataset.py
> +        trailing_edges = trailing_edges[1:]
this makes sense to me, but it's subtle enough that it'd be nice to at least have a comment. I think I might also be leaning slightly towards the symmetrical approach (include extra leading edges too) since it's conceivable that we could end up using this function with a sub-section of a dataset.

2019-08-20 14:20 UTC, merged