Dataset pipeline tools
OsmoSystems/osmo-jupyter pull request #39
Opened 2019-11-08 20:37 UTC by EvanSimpson

[Asana Ticket](https://app.asana.com/0/819671808102776/1147536099838393)

Adds some tools to help clean up source data files more-so than the existing parse functions. Also adds a function to append experiment metadata to image file names.

I ended up cutting scope on a lot of inconsistencies I found in our historical data, that _should not_ appear going forward.

Things explicitly not supported:
 - kPA barometric pressure
- multiple YSI units for one experiment / in one csv file
- filtering out unequilibrated images
- Multiple source file types for one experiment (calibration + YSI, multiple YSI Formats)
- YSI files that do not conform to the normal column mappings
- Any simultaneous _Experiments_ should be part of separate _Attempts_ (prevent timestamp index collisions)

There's also an explicit dependency that any experiment that shows up in the data collection log needs to have a folder present locally in the local sync directory. I didn't think it was worth working around this since we have ticketed work to replace that with just getting listings directly from S3.

## Manual Testing
I prototyped building a dataset of everything currently on deepthought using these helper functions, and it should give a decent idea of how much work is left to finish this off (plus replacing local image search with S3).

[Notebook link](http://deepthought:8888/notebooks/Experiments/2019-11-08%20Librarify%20More%20Dataset%20Generation%20Process/2019-11-08%20Prototype%20Dataset%20Pipeline%20Tools.ipynb)

For those curious, 31 attempts resulted in about 35k data points and roughly ~9MB (though I think there might be more opportunities to cut out some columns if necessary.

2019-11-12 21:52 UTC, jason-curtis approved these changes

2019-11-12 21:52 UTC, jason-curtis commented on osmo_jupyter/dataset/combine.py
> +    """ Get all image file names with associated experiment metadata.
this doc doesn't seem right

2019-11-12 21:52 UTC, jason-curtis commented on osmo_jupyter/dataset/source_files.py
> +def _check_filepath_is_valid(filepath):
nit: validity doesn't seem quite like the right thing to be checking here, and "data" seems like a helpful thing to mention 
```suggestion
def _is_data_filepath(filepath):
```

2019-11-12 21:52 UTC, jason-curtis commented on osmo_jupyter/dataset/source_files.py
> +def get_all_experiment_images(
note to readers: looks like this was just moved from `.combine`

2019-11-12 21:52 UTC, jason-curtis commented on osmo_jupyter/dataset/transform.py
> +import datetime
minor: I'm not a huge fan of the name `transform` for this file. It's very generic. It feels a bit more like `load`ing or `normaliz`ing files? don't love those either.

2019-11-12 21:52 UTC, jason-curtis commented on osmo_jupyter/dataset/transform.py
> +import datetime
maybe the problem is that we're trying to do too much with module names. the challenge I was having here is that I saw the filename and thought "well that could be anything". The logical line between this and the `parse` module is fuzzy to me, since that one is also doing some normalization. maybe we should start using module-level docstrings to explain what each module is for?

2019-11-12 22:33 UTC, jaimemarijke approved these changes

2019-11-12 22:33 UTC, jaimemarijke commented on osmo_jupyter/dataset/parse.py
> +def parse_ysi_prosolo_file(filepath: str) -> pd.DataFrame:
nice, I'd been thinking we should make this change

2019-11-12 22:33 UTC, jaimemarijke commented on osmo_jupyter/dataset/source_files.py
> +VALID_FILETYPES = [".csv", ".mp4", ".gif"]
might want to add a comment explaining why we expect each of these. for example, I'm not sure why we'd want anything other than .csvs when we are building the dataset

2019-11-12 22:33 UTC, jaimemarijke commented on osmo_jupyter/dataset/source_files.py
> +    return all_images.drop(all_images[~all_images["image"].str.contains("jpeg")].index)
minor: Could this filtering happen in the list comprehension instead?

```
all_images = [
            ...
            for file in os.listdir(os.path.join(local_sync_directory, experiment_name))
            if file.endswith('.jpeg')
        ],
```

2019-11-12 22:33 UTC, jaimemarijke commented on osmo_jupyter/dataset/source_files.py
> +            {"experiment": experiment_name, "image": image}
nit: seems like we might want to be consistent about using either `experiment` or `experiment_name`

2019-11-12 22:33 UTC, jaimemarijke commented on osmo_jupyter/dataset/source_files.py
> +VALID_FILETYPES = [".csv", ".mp4", ".gif"]
also, nit: "valid" doesn't seem like quite the right word here, maybe just because it's not clear to me what makes something valid or not. maybe this could be `SOURCE_DATA_FILETYPES`

2019-11-12 22:33 UTC, jaimemarijke commented on osmo_jupyter/dataset/transform.py
> +    TEMPERATURE_C,
Maybe these should live in a separate shared file, e.g. `constants.py`. It doesn't seem like `parse` has any more right to own them than `transform` does

2019-11-12 22:33 UTC, jaimemarijke commented on osmo_jupyter/dataset/transform.py
> +    TEMPERATURE_C,
ohh, also I assumed these were constant numbers but from context here it looks like they are labels? that should probably be in the name somehow, e.g. `DO_PCT_LABEL` or something

2019-11-12 22:33 UTC, jaimemarijke commented on osmo_jupyter/dataset/transform.py
> +    pd.testing.assert_frame_equal(dataset, dataset.sort_index())
since you're going to the work to get the sorted version to compare to, maybe this should just do the sorting and not worry whether it was or wasn't already sorted?

2019-11-12 22:33 UTC, jaimemarijke commented on osmo_jupyter/dataset/transform.py
> +def _generate_time_based_setpoint_ids(dataset):
minor/major: hmm.... this seems a bit brittle, since it relies on our existing practice of always staying at a setpoint for 5 min, which might change. 

Alternate (more complicated) idea: determine setpoint IDs by grouping temporally sequential rows that have "the same" DO/temperature value to within some threshold.

2019-11-12 22:33 UTC, jaimemarijke commented on osmo_jupyter/dataset/transform.py
> +        barometric_pressure_mmhg=ysi_data["YSI barometric pressure (mmHg)"],
should these use the `DO_PCT` and `BAROMETRIC_PRESSURE_MMHG ` constants?

2019-11-12 22:33 UTC, jaimemarijke commented on osmo_jupyter/dataset/transform.py
> +    return _prepare_ysi_data(ysi_kordss_data)
s/kordss/prosolo

2019-11-12 23:10 UTC, jason-curtis requested changes
noticed an issue when looking at the other review that I think merits a change

2019-11-12 23:10 UTC, jason-curtis commented on osmo_jupyter/dataset/source_files.py
> +    return all_images.drop(all_images[~all_images["image"].str.contains("jpeg")].index)
(came back here as I noticed this issue in the other PR)
major: checking that the filename contains `jpeg` seems risky since it'll accept files like `not_a_jpeg.txt`. It should be pretty easy to do something a little more airtight, checking that filenames end with `.jpeg` or at least including the dot in the `contains` check.

EDIT: it looks like you can use [`Series.str.contains()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.contains.html) with `regex=True` or even [`Series.str.endswith()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.endswith.html)

2019-11-12 23:36 UTC, jaimemarijke requested changes

2019-11-12 23:36 UTC, jaimemarijke commented on osmo_jupyter/dataset/combine.py
> +    images_by_experiment["cartridge_id"] = experiment_metadata["cartridge_id"]
I'm a little confused how this works. I'm assuming the `experiment_metadata` df has one row per experiment, so I'm not clear how this propagates over to the `images_by_experiment` df, which has multiple rows per experiment.

2019-11-12 23:36 UTC, jaimemarijke commented on osmo_jupyter/dataset/source_files.py
> +def get_all_experiment_images(
maybe this should be `get_all_experiment_image_filenames` since it doesn't actually get images, and the important thing is that it's finding all the filenames

2019-11-12 23:36 UTC, jaimemarijke commented on osmo_jupyter/dataset/combine.py
> +    images_by_experiment = get_all_experiment_images(
(I started making this comment on your other PR, but realized it fit better here).

change requested: some renaming of these functions.

It strikes me that without reading the specifics of the two functions, `get_all_experiment_images ` and `get_images_by_experiment` sound very similar, and it's hard to know what to expect from them. 

I think `get_images_by_experiment` is a bit of a misnomer, since that implies that it returns something grouped or keyed by experiment, which it doesn't. Also, aside from calling `get_all_experiment_images`, the actual logic in this function looks like it has more to do with the other experiment metadata than the images.

2019-11-12 23:36 UTC, jaimemarijke commented on osmo_jupyter/dataset/combine.py
> +    """ Get all image file names with associated experiment metadata.
+1 could definitely use more documentation here.

2019-11-12 23:36 UTC, jaimemarijke commented on osmo_jupyter/dataset/combine.py
> +    images_by_experiment["cartridge_id"] = experiment_metadata["cartridge_id"]
Ah, I believe my confusion stems from the fact that `experiment_metadata` is actually a series - basically just a single row from the data collection log, which might have multiple "experiments" but a single cartridge, cosmobot, etc. 

Maybe it would be more correct to call this `attempt_metadata`, since I believe we've settled on "attempt" as the terminology for a grouping of "experiments"

2019-11-12 23:38 UTC, jaimemarijke commented on osmo_jupyter/dataset/source_files.py
> +    return all_images.drop(all_images[~all_images["image"].str.contains("jpeg")].index)
+1 I meant to call out the part about .endswith vs .contains as something to change even if you choose not to move the filtering itself to the list comprehension

2019-11-12 23:39 UTC, jaimemarijke commented on osmo_jupyter/dataset/source_files.py
> +def _check_filepath_is_valid(filepath):
+1 I had a similar comment about the module constant name

2019-11-12 23:44 UTC, rush340 commented on osmo_jupyter/dataset/transform.py
> +def _generate_time_based_setpoint_ids(dataset):
It's only relying on equilibration between setpoints taking >5 mins and the time between consecutive image captures at a setpoint being <5 mins. Maybe a comment about those assumptions would help.

It still feels a little brittle. I think I called that out on Slack when I originally went with this method in the notebook. I originally had it doing the alternate idea you're describing, but that won't differentiate the identical setpoints at the point where a sweep reversed.

2019-11-13 15:53 UTC, EvanSimpson commented on osmo_jupyter/dataset/transform.py
> +import datetime
I also struggled a lot with this and really don't know what to do. I don't think this is `load`ing  because that has a specific meaning in data pipelining in "Extract-Transform-Load". "Load" for us would seemingly just be calling `.to_csv` and committing the file. We have "Extract" partially split up between `source_files` and `parse` and then "Transform" split amongst `parse`, `transform`, and `combine`.

It's a real mess.

I think the best option is to just move the `transform` code back into `parse`, since it's not much and they do thematically similar things.

2019-11-13 16:39 UTC, EvanSimpson commented on osmo_jupyter/dataset/combine.py
> +    images_by_experiment = get_all_experiment_images(
I renamed one of these to use `attempt` rather than `experiment` so the distinction should be clearer now.

2019-11-13 21:46 UTC, jason-curtis commented on osmo_jupyter/dataset/transform.py
> +import datetime
yeah I have the same thought about ETL also. I'm not a fan of that acronym though it *is* catchy. Looks like you merged 'em, I'll take a look.

2019-11-13 22:27 UTC, jason-curtis approved these changes

2019-11-13 22:27 UTC, jason-curtis commented on osmo_jupyter/dataset/parse.py
> +        Numerical values are rounded.
:+1: I like this framing of these functions. It feels about right for now that the functions that do the most are `process_*_file()`

2019-11-13 22:27 UTC, jason-curtis commented on osmo_jupyter/dataset/parse_test.py
> +            # Rounded to at most 6 sigfigs
minor: I don't think [`pd.testing.assert_frame_equal`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.testing.assert_frame_equal.html) checks this deep by default. I think it only checks the first 5 decimal points unless you ask for something different.

2019-11-14 16:32 UTC, rush340 approved these changes

2019-11-15 14:23 UTC, merged