Fix dataset helper function issues and use S3 to get experiment images
OsmoSystems/osmo-jupyter pull request #41
Opened 2019-11-12 21:45 UTC by EvanSimpson

[Asana Ticket](https://app.asana.com/0/819671808102776/1148349932180745)

This is a diff on #39 - we could either review them together, or go through the review process for #39 first, then tackle this one after it's been merged. I don't have a strong preference.

Notably, I removed the AWS credentials from the call to `boto.connect_s3()` so there's now a strict dependency that there be credentials in the calling env / a `.aws/credentials` file. This shouldn't be a huge issue since both workstation have that, and this will most likely be called from workstation jupyter notebooks.

### Bugfixes
* Fixes intermediate image-experiment dataframe column name usage.
* Interpolates calibration data to fill in gaps in sensor readings to align to more images.
* Stop adding setpoint IDs to raw calibration data - it's meant to be used on image timestamps.

## Manual Testing
Tried my prototype notebook locally with this change - wound up with about 38k images in total.

2019-11-12 23:06 UTC, jason-curtis approved these changes
nice work removing the creds. I don't remember why those were living there but I think must have been having some initial setup issue.

2019-11-12 23:06 UTC, jason-curtis commented on osmo_jupyter/dataset/source_files.py
> +# COPY PASTA - from cosmobot-process-experiment
it'd be nice to be more specific here and below
```suggestion
# COPY PASTA - from cosmobot-process-experiment - osmo_camera.s3
```
could even include the revision # in there...

2019-11-12 23:06 UTC, jason-curtis commented on osmo_jupyter/dataset/source_files.py
> +        return []
major: This seems like a critical enough error that it should explode, no?

2019-11-12 23:07 UTC, jason-curtis requested changes
previous review should have been "request changes" because of the one error handling thing

2019-11-12 23:36 UTC, jaimemarijke approved these changes

2019-11-12 23:36 UTC, jaimemarijke commented on osmo_jupyter/dataset/source_files.py
> +CAMERA_SENSOR_EXPERIMENTS_BUCKET_NAME = "camera-sensor-experiments"
:P "camera sensor experiments" is a kind of old name. maybe the constant should just be `EXPERIMENTS_BUCKET_NAME`

2019-11-12 23:36 UTC, jaimemarijke commented on osmo_jupyter/dataset/source_files.py
> +def list_camera_sensor_experiments_s3_bucket_contents(
nit: similar comment as above - I'm thinking we should phase out the "camera sensor experiments" name, since that's not really how we talk about it anymore, and just use "experiments" or "cosmobot experiments" instead

update: I didn't realize this was the original fn name. I suppose there's something to be said to try to keep the copy-pasta'd functions as similar as possible to facilitate future refactoring, but right now I'm thinking it would be better to just factor and name these functions however we want them to be for this code.

2019-11-12 23:36 UTC, jaimemarijke commented on osmo_jupyter/dataset/source_files.py
> +def list_camera_sensor_experiments_s3_bucket_contents(
other nit: could be underscore-prefixed

2019-11-12 23:55 UTC, jason-curtis commented on osmo_jupyter/dataset/source_files.py
> +def list_camera_sensor_experiments_s3_bucket_contents(
hmm I'm thinking this now too. there isn't really that much copypasta'd code and much some of it is modified. *maybe* (just maybe) we should just not be apologetic about having similar, but different code in two different packages for two different purposes.

2019-11-13 00:01 UTC, rush340 approved these changes

2019-11-13 00:05 UTC, rush340 commented on osmo_jupyter/dataset/source_files.py
> +def list_camera_sensor_experiments_s3_bucket_contents(
What if it were [three](https://github.com/OsmoSystems/cosmobot-run-experiment/blob/master/cosmobot_run_experiment/s3.py#L46) different packages?  :P 

I'm all for a better function name. We could put the original in another comment above it if we want traceability.

2019-11-15 18:51 UTC, EvanSimpson commented
I added in a bugfix+test fix for an issue I found in the last PR.

2019-11-18 17:18 UTC, jaimemarijke approved these changes

2019-11-18 17:30 UTC, jason-curtis requested changes

2019-11-18 17:30 UTC, jason-curtis commented on osmo_jupyter/dataset/combine.py
>              A DataFrame of images filenames along with timestamp, experiment name, and
since we're having issues with column names, maybe this docstring should be more specific about column names?

2019-11-18 17:30 UTC, jason-curtis commented on osmo_jupyter/dataset/source_files.py
>              DataFrame of all image file names and the corresponding experiment name.
same note about this docstring - could be more specific on column names

2019-11-18 17:30 UTC, jason-curtis commented on osmo_jupyter/dataset/parse.py
> +    setpoint_transitions = image_data_sorted.index.to_series().diff() > datetime.timedelta(
previously it was leaning on a concept of a `calibration_log` convention which kiiiinda implied indexing by timestamp, but with the name change (`calibration_log_data` -> `image_data`) it's even less clear that we expect this to be indexed on timestamp.

Maybe we should just change this function to take a Series of timestamps?

2019-11-18 17:30 UTC, jason-curtis commented on osmo_jupyter/dataset/parse.py
> +    rounded_calibration_data = calibration_data_resampled.round(
did you mean to remove setpoint ID generation here? if so we should remove it from the docstring too.

2019-11-18 17:30 UTC, jason-curtis commented on osmo_jupyter/dataset/parse_test.py
> +def test_intertoplates_calibration_log_data_correctly(mocker):
```suggestion
def test_interpolates_calibration_log_data_correctly(mocker):
```

2019-11-18 17:30 UTC, jason-curtis commented on osmo_jupyter/dataset/combine_test.py
> +                "experiment_name": [
is there anything downstream (jupyter snippets, maybe) that needs to know about these column name changes?

2019-11-19 14:44 UTC, EvanSimpson commented on osmo_jupyter/dataset/parse.py
> +    rounded_calibration_data = calibration_data_resampled.round(
As per offline discussion - yes setpoint ID generation as implemented above needs to be applied to image timestamps, and not calibration timestamps.

2019-11-19 14:45 UTC, EvanSimpson commented on osmo_jupyter/dataset/combine_test.py
> +                "experiment_name": [
I don't think so, so far. Would only affect the end consumer, of which there aren't any yet.

2019-11-19 18:33 UTC, jason-curtis approved these changes

2019-11-19 19:00 UTC, rush340 approved these changes

2019-11-19 19:59 UTC, merged